### ISSUE TITLE
How to install this package?

### ISSUE THREAD

**Issue by leolux** [dbrock/node-regexp-quote#5]
Both commands result in npm ERR! code E404 npm ERR! 404 Not Found: regex-quote@latest

```
npm install regexp-quote
npm install node-regexp-quote
```

**Comment by leolux** [comment]
I am running npm version 5.0.0

**Comment by dbrock** [comment]
Very strange... Let me know if you find out!

**Comment by leolux** [comment]
Cleaning the npm cache didn't help. But after downloading and reinstalling node.js everything works again. In addition to that I removed many global packages in favour of local (project dependent) packages.  As the cause of the issue seems to be independent of this project I will close it.
